### ISSUE TITLE
关于iOS传值回flutter的EventChannel问题

### ISSUE THREAD

**Issue by OmgKevin** [soragui/flutter_baidu_speech_plugin#1]
直接上代码：flutter端：
import 'dart:async';
import 'package:flutter/services.dart';

class FlutterTestEventchanelPlugin {

  static const MethodChannel _channel = const MethodChannel('flutter_test_eventchanel_plugin');
  static const EventChannel _channel2 = const EventChannel('student_event');

  String mResult;
  Function(String) mFunction;

  void init(Function(String) func) {
    _channel2.receiveBroadcastStream().listen(_onEvent, onError: _onError);
    mFunction = func;
  }

  void _onEvent(Object event) {
    mResult = event;
    print('---------event---------');
    print(event);
    if (mFunction != null) {
      mFunction(event);
    }
  }

  void _onError(Object error) {
    mResult = error;
    print(error);
    if (mFunction != null) {
      mFunction(error);
    }
  }
  static Future<String> get platformVersion async {
    final String version = await _channel.invokeMethod('getPlatformVersion');
    return version;
  }
  static Future<void> getnativecanshu() async {
    await _channel.invokeMethod("getnativecanshu");
  }
}

iOS端代码：
#import "FlutterTestEventchanelPlugin.h"

@interface FlutterTestEventchanelPlugin ( )<FlutterStreamHandler>
@property (nonatomic, copy) FlutterEventSink eventSink;
@end

@implementation FlutterTestEventchanelPlugin
+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar {
    
  FlutterMethodChannel* channel = [FlutterMethodChannel  methodChannelWithName:@"flutter_test_eventchanel_plugin"
            binaryMessenger:[registrar messenger]];
    
    
    FlutterEventChannel *channel2 = [FlutterEventChannel eventChannelWithName:@"student_event" binaryMessenger:[registrar messenger]];
    
  FlutterTestEventchanelPlugin* instance = [[FlutterTestEventchanelPlugin alloc] init];
  [registrar addMethodCallDelegate:instance channel:channel];
    
    [channel2 setStreamHandler:instance];
    
}

#pragma mark - FlutterStreamHandler
- (FlutterError* _Nullable)onListenWithArguments:(id _Nullable)arguments
                                       eventSink:(FlutterEventSink)events {
    
    self.eventSink = events;
    return nil;
}

- (FlutterError* _Nullable)onCancelWithArguments:(id _Nullable)arguments{
    return nil;
}

- (void)handleMethodCall:(FlutterMethodCall*)call result:(FlutterResult)result {
    
  if ([@"getPlatformVersion" isEqualToString:call.method]) {
      
    result([@"iOS " stringByAppendingString:[[UIDevice currentDevice] systemVersion]]);
      
  }if ([@"getnativecanshu" isEqualToString:call.method]) {
      
      self.eventSink(@"测试数据回传flutter");
  }
    else {
    result(FlutterMethodNotImplemented);
  }
}

@end

xcode运行时，崩溃在 self.eventSink(@"测试数据回传flutter"); 这一句，崩溃信息：
Thread 1: EXC_BAD_ACCESS (code=1, address=0x10)

可以帮我找下问题的原因嘛，多谢多谢

**Comment by OmgKevin** [comment]
已经解决

**Comment by fupingren** [comment]
我也遇到这个问题，调试好几天了，麻烦问下你是怎么解决的？

**Comment by fupingren** [comment]
> 已经解决

我也遇到这个问题，调试好几天了，麻烦问下你是怎么解决的？

**Comment by shijinliang** [comment]
> > 已经解决
> 
> 我也遇到这个问题，调试好几天了，麻烦问下你是怎么解决的？

self.eventSink调用之前做一下判空处理，有可能是空的，这一块是异步的。调用太早的话可能是空的

**Comment by fupingren** [comment]
> > > 已经解决
> > 
> > 
> > 我也遇到这个问题，调试好几天了，麻烦问下你是怎么解决的？
> 
> self.eventSink调用之前做一下判空处理，有可能是空的，这一块是异步的。调用太早的话可能是空的

多谢，解决了闪退问题。还有http通信也要配置权限。
